title: AI Blog
description: ხელოვნური ინტელექტი - მანქანები სწავლობენ
theme: just-the-docs

url: https://aiblog.ge 

aux_links:
  bitcamp.ge: https://bitcamp.ge
  Oto Zakalashvili: https://www.facebook.com/otarza